ProyectoPartidoPolitico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include ('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .import views


app_name = 'app'
urlpatterns = [
    # url(r'hitcount/',include('hitcount.urls', namespace='hitcount')),
    path('', views.index, name='index'),
    # Requerimiento 1, 2, 3
    path('inicio/', views.inicio_sesion_view, name="inicio_sesion_view"),
    path('post_inicio/', views.iniciar_sesion_post, name ='iniciar_sesion_post'),
    path('registrarse/', views.registrarse_view, name='registrarse_view'),
    path('registrase_post', views.registrarse_post, name="registrarse_post"),
    path('cerrar/', views.cerrar_sesion, name='cerrar_sesion'),
    # Home de administrador y ciudadano
    path('administrador/', views.pagina_administrador_view, name="pagina_administrador_view"),
    path('ciudadano/', views.pagina_ciudadano_view, name="pagina_ciudadano_view"),
    # Requerimiento 4
    path('CambiarDatosCuentaP/', views.CambiarDatosCuentaP_view, name='CambiarDatosCuentaP'),
    path('CambiarDatosCuentaPOSTP/<int:id_user>', views.CambiarDatosCuentaPOSTP, name='CambiarDatosCuentaPOSTP'),
    path('CambioExitosoP/', views.CambioExitosoP_view, name='CambioExitosoP'),
    path('ErrorCambioDatosP', views.ErrorCambioDatosP_view, name='ErrorCambioDatosP'),
    # Requerimiento 5
    path('CrearPartidoPoliticoP/', views.CrearPartidoPoliticoP_view, name='CrearPartidoPoliticoP_view'),
    path('CrearPartidoPoliticoFormP/', views.CrearPartidoPoliticoFormP_view, name='CrearPartidoPoliticoFormP'),
    path('CrearPartidoPoliticoPOSTP/', views.CrearPartidoPoliticoPOSTP, name='CrearPartidoPoliticoPOSTP'),
    # Requerimiento 6
    path('ConsultarListaPartidosPoliticosAP/', views.ConsultarListaPartidosPoliticosAP_view, name='ConsultarListaPartidosPoliticosAP_view'),
    path('ConsultarListaPartidosPoliticosCP/', views.ConsultarListaPartidosPoliticosCP_view, name='ConsultarListaPartidosPoliticosCP_view'),
    # Requerimiento 7
    path('ConsultarPartidoPoliticoSAR/',views.ConsultarPartidoPoliticoSAR_view, name= 'ConsultarPartidoPoliticoSAR_view'),
    path('ConsultarPPSAR',views.ConsultarPPSAR_post, name= 'ConsultarPPSAR_post'),
    # Requerimiento 8
    path('administrador/Crear',views.CrearIndividuoASAR_view, name= 'CrearIndividuoASAR_view'),
    path('administrador/CrearIndividuo',views.CrearIndividuoASAR_post, name= 'CrearIndividuoASAR_post'),
    path('ciudadano/Crear',views.CrearIndividuoCSAR_view, name= 'CrearIndividuoCSAR_view'),
    path('ciudadano/CrearIndividuo',views.CrearIndividuoCSAR_post, name= 'CrearIndividuoCSAR_post'),
    path('CreacionExitosa/', views.CreacionExitosa_view, name='CreacionExitosa_view'),
    path('CreacionPendiente/', views.CreacionPendinte_view, name='CreacionPendiente_view'),
    # Requerimiento 9
    path('administrador/AprobarIndividuo',views.AprobarIndividuoSAR_view, name= 'AprobarIndividuoSAR_view'),
    path('administrador/AprobarIndividuoSAR',views.AprobarIndividuoSAR_post, name= 'AprobarIndividuoSAR_post'),
    path('AprobarExitoso/', views.AprobarExitoso_view, name='AprobarExitoso_view'),
    # Requerimiento 10
    path('ConsultarListaIndiCP', views.ConsultarListaIndiCP_view, name = 'ConsultarListaIndiCP_view'),
    path('ConsultarListaIndiAP', views.ConsultarListaIndiAP_view, name = 'ConsultarListaIndiAP_view'),
    # Requerimiento 11
    path('ConsultarIndividuo', views.ConsultarIndividuo_view, name = 'ConsultarIndividuo_view'),
    path('ConsultarIndividuoP', views.ConsultarIndividuo_post, name = 'ConsultarIndividuo_post'),
    # Requerimiento 12
    path('administrador/AfiliarIndividuo', views.AfiliarIndividuoASAR_view, name = 'AfiliarIndividuoASAR_view'),
    path('ciudadano/AfiliarIndividuo', views.AfiliarIndividuoCSAR_view, name = 'AfiliarIndividuoCSAR_view'),
    path('administrador/AfiliarIndividuoP', views.AfiliarIndividuoASAR_post, name = 'AfiliarIndividuoASAR_post'),
    path('ciudadano/AfiliarIndividuoP', views.AfiliarIndividuoCSAR_post, name = 'AfiliarIndividuoCSAR_post'),
    # Requerimiento 13
    path('administrador/AprobarAfiliacion',views.AprobarAfiliacionSAR_view, name= 'AprobarAfiliacionSAR_view'),
    path('administrador/AprobarAfiliacionSAR',views.AprobarAfiliacionSAR_post, name= 'AprobarAfiliacionSAR_post'),
    # Requerimiento 14
    path('administrador/CrearProceso', views.CrearProcesoASAR_view, name = 'CrearProcesoASAR_view'),
    path('ciudadano/CrearProceso', views.CrearProcesoCSAR_view, name = 'CrearProcesoCSAR_view'),
    path('administrador/CrearProcesoP', views.CrearProcesoASAR_post, name = 'CrearProcesoASAR_post'),
    path('ciudadano/CrearProcesoP', views.CrearProcesoCSAR_post, name = 'CrearProcesoCSAR_post'),
    # Requerimiento 15
    path('administrador/AprobarProceso',views.AprobarProcesoASAR_view, name= 'AprobarProcesoASAR_view'),
    path('administrador/AprobarProcesoSAR',views.AprobarProcesoASAR_post, name= 'AprobarProcesoASAR_post'),
    # Requerimiento 16
    path('administrador/ImplicarAfiliado', views.ImplicarAfiliadoASAR_view, name = 'ImplicarAfiliadoASAR_view'),
    path('ciudadano/ImplicarAfiliado', views.ImplicarAfiliadoCSAR_view, name = 'ImplicarAfiliadoCSAR_view'),
    path('administrador/ImplicarAfiliadoP', views.ImplicarAfiliadoASAR_post, name = 'ImplicarAfiliadoASAR_post'),
    path('ciudadano/ImplicarAfiliadoP', views.ImplicarAfiliadoCSAR_post, name = 'ImplicarAfiliadoCSAR_post'),
    # Requerimiento 17
    path('ConsultarProceso', views.ConsultarProceso_view, name = 'ConsultarProceso_view'),
    path('ConsultarProcesoP', views.ConsultarProceso_post, name = 'ConsultarProceso_post'),
    # Requerimiento 18
    path('administrador/Habilitar-Deshabilitar',views.HabDesSAR_view, name= 'HabDesSAR_view'),
    path('administrador/HABDES',views.HabDesSAR_post, name= 'HabDesSAR_post'),
    path('HABDESExitoso/', views.HabDesEXI_view, name='HabDesEXI_view'),

    path('acerca/',views.acerca_view, name= 'acerca'),
    path('usuarios', views.usuarios_view, name='usuarios_view'),
    path('ErrorCuenta', views.ErrorCuenta_view, name='ErrorCuenta'),
    #path('error_registro', views.error_registro_view, name="error_registro_view")
]

app/templates/app/AfiliarIndividuoASAR.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Afiliar individuo a partido-Administrador</title>
    <link rel="stylesheet" href="{% static 'app/AfiliarIndividuoA.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">

</head>

<body>

    <div class="AfiliarIndividuoA">

        <div class="Header">
            <span id="titulo"> Afiliar Individuo A Partido-Administrador </span>
            <a href="{% url 'app:inicio_sesion_view' %}" id="link1">Regresar a página de inicio</a>
            <a href="{% url 'app:pagina_administrador_view' %}" id="link2">Regresar a página de inicio de administrador</a>
            <br>

        </div>

        <div class="OpcionesPAG">
            <i class="fas fa-search"></i>
            <span id="Descripción"> Bienvenido Administrador, aqui podras afiliar y aprobar un individuo que desee
                afiliarse</span>
        </div>

        <div class="Afiliar">
            <p id="TituloAfiliar"> AFILIAR
                <br>INDIVIDUO
            </p>
            <div class="boton1">
                <form method="POST" action="{% url 'app:AfiliarIndividuoASAR_post' %}">
                    {% csrf_token %}
                    <p id="TituloBoton1">Seleccione el ID del
                        <br>Individuo
                    </p>
                    <select name="individuo_id" id="ID">
                        {% for i in individuos %}
                        <option value="{{ i.id }}">{{ i.apellidos }} {{ i.nombres }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <br>
            </div>
            <div class="boton2">
                <p id="TituloBoton2">Seleccione el ID del
                    <br>Partido Politico
                </p>
                <select name="partido_id" id="Partido">
                    {% for p in partidos %}
                    <option value="{{ p.id }}">{{ p.nombre }}</option>
                    {% endfor %}
                </select>
                <br>
                <br>

            </div>
            <div class="boton3">
                <p id="TituloBoton3">Seleccione la fecha de
                    <br> ingreso
                </p>
                <input type="date" id="fecha1" name="fecha-ingreso" required>
                <br>
                <br>

            </div>
            <div class="boton4">
                <p id="TituloBoton4">Seleccione la fecha de
                    <br> salida
                </p>
                <input type="date" id="fecha2" name="fecha-salida">
                <br>
                <br>

            </div>
            <div class="boton5">
                <input type="submit" value="Completar Afiliación">
                <br>
            </div>

            </form>

        </div>
        <div class="Footer">
            <img src="ImagenesP/IMAGEN2.png" alt="IMAGEN REDES SOCIALES" id="imagen2">

        </div>

    </div>

</body>

</html>

app/templates/app/AfiliarIndividuoCSAR.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/AfiliarIndividuoC.css' %}">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Afiliar Individuo - Ciudadano</title>
</head>

<body>
    <div class="AfiliarIndividuoC">
        <div class="Header">
            <i class="fas fa-tree"></i>
            <span id="titulo">Afiliar Individuo A Partido - Ciudadano</span>
            <a href="{% url 'app:inicio_sesion_view' %}" target="_blank" id="link1">INICIO</a>
            <a href="{% url 'app:pagina_ciudadano_view' %}" target="_blank" id="link2">PAGINA CIUDADANO</a>

        </div>


        <div class="Descripcion">
            <i class="fas fa-tree"></i>
            <span id="descripcion1"> ¡Bienvenido Ciudadano! Aqui puedes afiliar un ciudadano a un partido
                politico</span>
            <br>
            <br>
            <span id="descripcion2">Tú Afiliación será aprobada por un administrador proximamente</span>


            <div class="Afiliar">
                <p id="TituloAfiliar"> AFILIAR
                    <br>INDIVIDUO
                </p>
                <form method="POST" action="{% url 'app:AfiliarIndividuoCSAR_post' %}"></form>
                {% csrf_token %}
                <div class="cuadro1">
                    <p id="TituloBoton1">Seleccione el ID del
                        <br>Individuo
                    </p>
                    <select name="individuo_id" id="ID">
                        {% for i in individuos %}
                        <option value="{{ i.id }}">{{ i.apellidos }} {{ i.nombres }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <br>
                </div>
                <div class="cuadro2">
                    <p id="TituloBoton2">Seleccione el ID del
                        <br>Partido Politico
                    </p>
                    <select name="partido_id" id="Partido">
                        {% for p in partidos %}
                        <option value="{{ p.id }}">{{ p.nombre }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <br>

                </div>
                <div class="cuadro3">
                    <p id="TituloBoton3">Seleccione la fecha de
                        <br> ingreso
                    </p>
                    <input type="date" id="fecha1" name="fecha-ingreso" required>
                    <br>
                    <br>

                </div>
                <div class="cuadro4">
                    <p id="TituloBoton4">Seleccione la fecha de
                        <br> salida
                    </p>
                    <input type="date" id="fecha2" name="fecha-salida">
                    <br>
                    <br>

                </div>
                <div class="cuadro5">
                    <input type="submit" id="boton1" value="Completar Afiliación">
                    <br>
                </div>

                </form>

            </div>

            <div class="Footer">

                <img src="ImagenesP/IMAGEN2.png" alt="IMAGEN REDES SOCIALES" id="imagen2">

            </div>

        </div>
</body>

</html>

app/templates/app/CambioExitosoP.html
{% load static %}
<!-- {% load hitcount_tags %} -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cultura Democrática</title>
    <link rel="stylesheet" href="{% static 'app/EstilosCambiarDatosCuentaP.css' %}">
    <!-- <link rel="stylesheet" href="EstilosV/Estilos4VA.css"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
</head>
<body>

    <div class="contenedor6">
        <div class="cuadro6" style="border-left-width: 250px;border-right-width: 300px;">
            <br>
            <h1>Cambio exitoso</h1>
            <p>¡Sus datos datos han sido cambiados exitosamente!</p>
            <br>
            <a href="{% url 'app:pagina_administrador_view' %}" id="link3" style="padding-right: 300px;padding-left: 320px; width: 900px;">Regresar a página de inicio de administrador</a>
            <a href="{% url 'app:cerrar_sesion' %}" id="link3" style="padding-right: 300px;padding-left: 320px; width: 900px;">Cerrar sesión</a>
            <!-- <a href="PaginaAdminVA.html">Regresar a la página de incio</a> -->
            <!-- <a href="InicioVA.html">Cerrar sesión</a> -->
        </div>

        <div class="PiePagina">
            <img src="{% static 'app/IMAGEN2.png' %}" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>
    </div>

</body>
</html>

app/templates/app/ConsultarProceso.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultar proceso</title>
    <link rel="stylesheet" href="{% static 'app/Estilos_consultar_procesos.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="ConsultarProceso">
        <div class="BarraInicio">
            <i class="fas fa-search" id="logo1"></i>
            <span id="titulo">Consultar un Proceso</span>
        </div>
        <div class="Opciones">
            <i class="fas fa-search" id="logo2"></i>
            <span id="text1"> ¡ Aquí podrás consultar todos los procesos!</span>
            <br><br>
            <div class="cuadro1">
                <form action="{% url 'app:ConsultarProceso_post' %}" method="post">
                    {% csrf_token %}
                    <div class="cuadro5">
                        <fieldset>
                            <label for="proceso" id="text2">Seleccione un proceso</label>
                            <select name="proceso" id="ejemplo">
                                {% for p in procesos %}
                                    <option value="{{ p.id }}">
                                        {{ p.titulo }}
                                    </option>
                                {% endfor %}
                            </select>
                        </fieldset>
                    </div>
                    <button type="submit" id="boton">CONSULTAR PROCESO</button>
                </form>
            </div>
            <span>Recuerda que toda la información presentada está totalmente VERIFICADA</span>
            <br>
            <!-- <i class="fas fa-user-check fa-10x" id="logo3"></i><br> -->
            <a href="{% url 'app:inicio_sesion_view' %}" id="link1">Regresar a página de inicio</a><br>
            <a href="{% url 'app:pagina_ciudadano_view' %}" id="link3">Regresar a página de inicio de ciudadano</a><br>
            {% if request.user.is_superuser %}
                <a href="{% url 'app:pagina_administrador_view' %}" id="link3">
                    Regresar a página de inicio de administrador
                </a>
            {% endif %}
            {% if proceso != None %}
        <div>
            <p id="p1">Titulo: {{ proceso.titulo }}</p>
            <p id="p2">Fecha de Inicio: {{ proceso.fecha_inicio }}</p>
            <p id="p3">El proceso está {% if proceso.abierto %} abierto {% else %} cerrado {% endif %}</p>
            <p id="p4">Entidad: {{ proceso.entidad }}</p>
            <p id="p5">Monto: {{ proceso.monto }}</p>
            <p id="p6">Comentarios: {{ proceso.comentarios }}</p>
            <p id="p7">Visitas: {{ proceso.visitas }}</p>
            <h1 id="text2">Lista de Implicados:</h1>
            <table border="1" id="tabla1">
                <thead>
                    <tr>
                        <th colspan="8">Lista de implicados</th>
                    </tr>
                    <tr>
                        <th>Apellidos</th>
                        <th>Nombres</th>
                        <th>Partido Politico</th>
                        <th>Fecha de Acusación</th>
                        <th>Acusacion</th>
                        <th>Culpable/Inocente</th>
                        <th>Pena</th>
                        <th>Comentarios</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in implicados %}
                    <tr>
                        <td id="td8">{{ i.afiliado.individuo.apellidos }}</td>
                        <td id="td9">{{ i.afiliado.individuo.nombres }}</td>
                        <td id="td10">{{ i.afiliado.partido.nombre }}</td>
                        <td id="td11">{{ i.fecha }}</td>
                        <td id="td12">{{ i.acusacion }}</td>
                        <td id="td13">{% if i.culpable %} Culpable {% else %} Inocente {% endif %}</td>
                        <td id="td14">{{ i.pena }}</td>
                        <td id="td15">{{ i.comentarios }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
        </div>
        
        <div class="PiePagina">
            <img src="Imagenes/IMAGEN2.png" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>
    </div>
</body>

</html>

app/templates/app/CrearIndividuoASAR.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear individuo</title>
    <link rel="stylesheet" href="{% static 'app/CrearIndividuoASAR.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

    <div class="CrearIndividuoAP">
        <div class="BarraInicio">
            <i class="fas fa-plus-circle" id="logo1"></i>
            <span id="titulo">Crear individuo</span>
        </div>
        <div class="Opciones">
            <i class="fas fa-plus-circle" id="logo2"></i>
            <span id="text1">Bienvenido administrador, aquí podrás crear a un individuo, suerte !</span>

            <div class="cuadro1" style="margin-left: 300px;">
                <span id="text2">CREAR INDIVIDUO</span>
                <form action="{% url 'app:CrearIndividuoASAR_post' %}" method="post">
                    {% csrf_token %}
                    <div class="cuadro2">
                    </div>
                    <div class="cuadro3">
                        <fieldset>
                            <label for="Nombres" id="label1">Ingrese el Nombre</label>
                            <input type="text" name="nombre" placeholder="Nombre individuo">
                        </fieldset>
                    </div>
                    <div class="cuadro4">
                        <fieldset>
                            <label for="Apellidos" id="label2">Ingrese los apellidos</label>
                            <input type="text" name="apellidos" placeholder="Apellidos individuo">
                        </fieldset>
                    </div>
                    <div class="cuadro5">
                        <fieldset>
                            <label for="Fecha" id="label3">Ingrese fecha de nacimiento del individuo</label>
                            <input type="date" name="fechaN" placeholder="Fecha nacimiento">
                        </fieldset>
                    </div>
                    <br>
                    <button type="submit" id="boton1">CREAR INDIVIDUO</button>
                </form>
            </div>
            <br>
            <br>
            <a href="{% url 'app:AprobarIndividuoSAR_view' %}" id="link2" style="margin-left: 550px">Quiero aprobar
                individuos</a>
            <br>
            <a href="{% url 'app:inicio_sesion_view' %}" target="_blank" id="link1" style="padding-left: 550px">Regresar
                a página de inicio</a><br>

        </div>
    </div>
    <div class="PiePagina">
        <img src="ImagenesP/IMAGEN2.png" alt="IMAGEN REDES SOCIALES" id="imagen2">
    </div>
    </div>
</body>

</html>

app/templates/app/PaginaAdminV.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cultura Democrática</title>
    <link rel="stylesheet" href="{% static 'app/EstilosPaginaAdminV.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
</head>
<body>

    <div class="contenedor4">
        <div class="BarraInicial">
            <button><i class="fas fa-bars fa-2x"></i></button>  
        </div>
        <div class="texto1">
            <br>
            <h1>Bienvenido Administrador {{ request.user.first_name }}</h1>
            <br>
            <p>¡Mira todas la opciones que tenemos para ti desplegando el menu a la derecha!</p>
            <br>
            <h3>Misión</h3>
            <p>Este sitio web tiene como misión informar a todos los ciudadanos de Colombia sobre como esta la situación politica del pais en materia de corrupción. Esta información sera importante en época de campaña, ya que podro conocer información a detaller de los partidos políticos y de cada uno de sus miembros</p>
            <br>
            <h3>Objetivo</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem nemo sed ad ea animi sequi repellendus officia consequuntur earum, quia ex perferendis doloremque amet minus rerum repellat reprehenderit deleniti accusamus?</p>
        </div>

        <div class="cuadro4">
            <br>
            <br>
            <a href="{% url 'app:CambiarDatosCuentaP' %}">Cambiar datos de la cuenta</a>
            <br>
            <br>
            <a href="{% url 'app:CrearPartidoPoliticoP_view' %}">Crear partido político</a>
            <br>
            <br>
            <a href="{% url 'app:ConsultarListaPartidosPoliticosAP_view' %}">Consultar lista partido político</a>

            <br>
            <br>
            <a href="{% url 'app:ConsultarPartidoPoliticoSAR_view' %}">Consultar partido político</a>

            <br>
            <br>
            <a href="{% url 'app:CrearIndividuoASAR_view' %}">Crear individuo</a>
            <br>
            <br>
            <a href="{% url 'app:ConsultarListaIndiAP_view' %}">Consultar Lista de individuo</a>
            <br>
            <br>
            <a href="{% url 'app:ConsultarIndividuo_view' %}">Consultar individuo </a>
            <br>
            <br>
            <a href="{% url 'app:AprobarIndividuoSAR_view' %}">Aprobar individuo </a>
            <br>
            <br>
            <a href="{% url 'app:AfiliarIndividuoASAR_view' %}">Afiliar individuos a partidos</a>
            <br>
            <br>
            <a href="{% url 'app:AprobarAfiliacionSAR_view' %}">Aprobar Afiliaciones</a>
            <br>
            <br>
            <a href="{% url 'app:CrearProcesoASAR_view' %}">Crear proceso</a>
            <br>
            <br>
            <a href="{% url 'app:AprobarProcesoASAR_view' %}">Aprobar proceso</a>
            <br>
            <br>
            <a href="{% url 'app:ConsultarProceso_view' %}">Consultar proceso</a>
            <br>
            <br>
            <a href="{% url 'app:ImplicarAfiliadoASAR_view' %}">Implicar un afiliado a proceso</a>
            <br>
            <br>
            <a href="{% url 'app:HabDesSAR_view' %}">Deshabilitar / Habilitar ciudadano</a>
            <br>
            <br>
            <a href="{% url 'app:cerrar_sesion' %}">Cerrar sesión</a>
        </div>

        <div class="PiePagina">
            <img src="{% static 'app/IMAGEN2.png' %}" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>

    </div>

</body>
</html>